language: perl
perl:
  - 5.8
  - 5.10
  - 5.12
  - 5.14
  - 5.16
  - 5.18
  - 5.20
  - 5.22
before_script:
  - "sudo apt-get install libexpat1-dev"
script: "perl Makefile.PL EXPATLIBPATH=$EXPATLIBPATH EXPATINCPATH=$EXPATINCPATH && make test"
after_failure:
  - "perl -V"
  - "perl -MData::Dumper -MConfig -e'print Dumper \\%Config'"
